server.port: 8080
spring:
  profiles:
    active: ${cluster_env}
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres?currentSchema=foodInc
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas: foodInc