spring:
  flyway:
    schemas: FOODINC
datasource:
  url: jdbc:postgresql://developer:mysecretpassword@db/foodinc
  username: developer
  password: mysecretpassword
  driver-class-name: org.postgresql.Driver